### ISSUE TITLE
Morning session peer to peer code review

### ISSUE THREAD

**Issue by harlexkhal** [Sboursen/to-do-tasks#4]
### Nice User interactions implemented while creating and editing tasks 👏  but there are a few issues i could find:

- You could do well to add form validations in your add task input, so a user don't get to insert a task with an empty description.

- It could have been nice if a task was edited and there was no content in its description it gets  automatically deleted
 
- According to the project requirements task indices are supposed to start counts from one(1) not zero(0)

**Comment by Sboursen** [comment]
Hi @harlexkhal,
Thanks for contributing to my project :pray: 
As for your suggestions, I was able to implement the following features:

- [x] I added a validation scheme to the principal Input field as well as to the description of the tasks.

- [x] Instead of the task being deleted if the description is empty, it will retain focus until the user change the description to a valid (alphanumeric) text.

Thanks again, and feel free to leave any comment below :arrow_double_down:
